### ISSUE TITLE
Question, what's the minimal version of OpenGL & OpenGL ES?

### ISSUE THREAD

**Issue by lygstate** [google/nxt-standalone#147]
Would nxt-standalone could be able compiled to WebGL or WebGL2 code?
For example, like https://github.com/floooh/oryol
Oryol seems not support for Computing but nxt-standalone support.
So maybe compute can be an optional feature?

**Comment by kainino0x** [comment]
No, it will not work on WebGL or OpenGL ES. The OpenGL backend, which requires OpenGL 4.5 (or 4.1 without compute) is a proof of concept, and it probably will not be possible to maintain forever due to fundamental incompatibilities of the API design with OpenGL.

NXT is a prototype of the next-generation "GPU for the Web" API, the goal of which is to make a new web graphics API that will solve performance and structural limitations of WebGL. Implementing it on top of WebGL would not be that useful since it would only change the shape of the API (though it could slightly help get a head start on porting). Something like NXT is expected to eventually ship natively in all major browsers, once we have standardized it.

**Comment by lygstate** [comment]
@kainino0x For mobile platforms, There are platforms that only support for OpenGL ES 3.0, would OpenGL ES 3.0 be enough?

**Comment by kainino0x** [comment]
No, I don't think it works with any version of OpenGL ES at all. Once we have a complete Vulkan backend, it could be made to work on Android. For iOS, we already have a Metal backend, but nothing has ever been built on iOS.

Ultimately this project is still a prototype and will most likely be replaced by some other open source library that serves the same function - implementing the final "GPU for the Web" API.
