### ISSUE TITLE
Inconsistent coordinate system

### ISSUE THREAD

**Issue by msiglreith** [google/nxt-standalone#162]
D3D12 seems to set the y-flip option for SPIRV-Cross.
GL doesn't and renders the triangle in the example upwards in contrast to D3D12.

**Comment by Kangz** [comment]
Unfortunately the coordinate systems have given us a lot more trouble than they should have. My understanding is that Vulkan D3D12 and GL all render to textures in the same orientation, however the present path for GL then shows this texture with (0, 0) at the bottom left instead of top-left for D3D12.

Also Metal is currently rendering to texture upside down :/

I will make a simple test to make sure all backends render to textures in the same orientation. The present path is hard to test automatically though. What we want is to settle on (0, 0) being at the top left.
